/* ==========================================================
   CoffeeLab - Oracle SQL (адаптированный под JPA имена)
   ========================================================== */

------------------------------------------------------------
-- 0) CLEANUP (опционально)
------------------------------------------------------------
/*
DROP VIEW v_sales_by_day;
DROP VIEW v_client_bonus_history;
DROP PROCEDURE p_complete_order;
DROP PROCEDURE p_spend_bonus;
DROP PROCEDURE p_add_item;
DROP PROCEDURE p_create_order;
DROP PROCEDURE p_register_client;
DROP TABLE bonus_txn;
DROP TABLE order_item;
DROP TABLE orders;
DROP TABLE product;
DROP TABLE product_category;
DROP TABLE client;
DROP TABLE users;
*/

------------------------------------------------------------
-- 1) TABLES (с именами как в JPA)
------------------------------------------------------------

-- Таблица users (соответствует @Entity User)
CREATE TABLE users (
                       id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       login          VARCHAR2(50)  NOT NULL UNIQUE,
                       password_hash  VARCHAR2(200) NOT NULL,
                       role           VARCHAR2(20)  NOT NULL CHECK (role IN ('BARISTA','ADMIN')),
                       created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Таблица client (соответствует @Entity Client)
CREATE TABLE client (
                        id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        phone          VARCHAR2(20) NOT NULL UNIQUE,
                        full_name      VARCHAR2(100),
                        bonus_balance  NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (bonus_balance >= 0),
                        created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Таблица product_category (соответствует @Entity ProductCategory)
CREATE TABLE product_category (
                                  id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR2(50) NOT NULL UNIQUE
);

-- Таблица product (соответствует @Entity Product)
CREATE TABLE product (
                         id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         category_id NUMBER NOT NULL REFERENCES product_category(id),
                         name        VARCHAR2(100) NOT NULL,
                         description VARCHAR2(400),
                         price       NUMBER(10,2) NOT NULL CHECK (price >= 0),
                         active      CHAR(1) DEFAULT 'Y' NOT NULL CHECK (active IN ('Y','N'))
);

-- Таблица orders (соответствует @Entity Order)
CREATE TABLE orders (
                        id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        client_id          NUMBER NULL REFERENCES client(id),
                        created_by_user_id NUMBER NOT NULL REFERENCES users(id),
                        status             VARCHAR2(20) DEFAULT 'NEW' NOT NULL
                     CHECK (status IN ('NEW','COMPLETED','CANCELED')),
                        subtotal           NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (subtotal >= 0),
                        bonus_spent        NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (bonus_spent >= 0),
                        total              NUMBER(12,2) DEFAULT 0 NOT NULL CHECK (total >= 0),
                        created_at         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                        completed_at       TIMESTAMP NULL
);

-- Таблица order_item (соответствует @Entity OrderItem)
CREATE TABLE order_item (
                            id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            order_id          NUMBER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                            product_id        NUMBER NOT NULL REFERENCES product(id),
                            product_name_snap VARCHAR2(100) NOT NULL,
                            unit_price_snap   NUMBER(10,2) NOT NULL,
                            qty               NUMBER(10) NOT NULL CHECK (qty > 0),
                            line_total        NUMBER(12,2) NOT NULL
);

-- Таблица bonus_txn (соответствует @Entity BonusTxn)
CREATE TABLE bonus_txn (
                           id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           client_id     NUMBER NOT NULL REFERENCES client(id),
                           order_id      NUMBER NULL REFERENCES orders(id),
                           txn_type      VARCHAR2(20) NOT NULL CHECK (txn_type IN ('EARN','SPEND')),
                           signed_amount NUMBER(12,2) NOT NULL CHECK (signed_amount <> 0),
                           reason        VARCHAR2(200),
                           created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- Индекс для защиты от двойного списания
CREATE UNIQUE INDEX ux_bonus_spend_once
    ON bonus_txn(order_id, txn_type);

------------------------------------------------------------
-- 2) PROCEDURES
------------------------------------------------------------

-- Регистрация клиента + приветственный бонус 50
CREATE OR REPLACE PROCEDURE p_register_client(
  p_phone      IN  VARCHAR2,
  p_full_name  IN  VARCHAR2,
  o_client_id  OUT NUMBER
) AS
BEGIN
INSERT INTO client(phone, full_name, bonus_balance)
VALUES (p_phone, p_full_name, 0)
    RETURNING id INTO o_client_id;

INSERT INTO bonus_txn(client_id, order_id, txn_type, signed_amount, reason)
VALUES (o_client_id, NULL, 'EARN', 50, 'Welcome bonus');

UPDATE client
SET bonus_balance = bonus_balance + 50
WHERE id = o_client_id;

COMMIT;
END;
/

-- Создать заказ
CREATE OR REPLACE PROCEDURE p_create_order(
  p_created_by IN NUMBER,
  p_phone      IN VARCHAR2,
  o_order_id   OUT NUMBER
) AS
  v_client_id NUMBER;
BEGIN
BEGIN
SELECT id INTO v_client_id
FROM client
WHERE phone = p_phone;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
      v_client_id := NULL;
END;

INSERT INTO orders(client_id, created_by_user_id)
VALUES (v_client_id, p_created_by)
    RETURNING id INTO o_order_id;

COMMIT;
END;
/

-- Добавить позицию
CREATE OR REPLACE PROCEDURE p_add_item(
  p_order_id   IN NUMBER,
  p_product_id IN NUMBER,
  p_qty        IN NUMBER
) AS
  v_name  product.name%TYPE;
  v_price product.price%TYPE;
BEGIN
SELECT name, price INTO v_name, v_price
FROM product
WHERE id = p_product_id
  AND active = 'Y';

INSERT INTO order_item(order_id, product_id, product_name_snap,
                       unit_price_snap, qty, line_total)
VALUES (p_order_id, p_product_id, v_name, v_price, p_qty,
        ROUND(v_price * p_qty, 2));

UPDATE orders
SET subtotal = (SELECT NVL(SUM(line_total), 0)
                FROM order_item WHERE order_id = p_order_id),
    total    = GREATEST(
            (SELECT NVL(SUM(line_total), 0)
             FROM order_item WHERE order_id = p_order_id)
                - bonus_spent, 0)
WHERE id = p_order_id;

COMMIT;
END;
/

-- Списание бонусов
CREATE OR REPLACE PROCEDURE p_spend_bonus(
  p_order_id IN NUMBER,
  p_amount   IN NUMBER
) AS
  v_client_id  NUMBER;
  v_subtotal   NUMBER(12,2);
  v_balance    NUMBER(12,2);
  v_limit      NUMBER(12,2);
  v_to_spend   NUMBER(12,2);
BEGIN
SELECT client_id, subtotal
INTO v_client_id, v_subtotal
FROM orders
WHERE id = p_order_id;

IF v_client_id IS NULL THEN
    RAISE_APPLICATION_ERROR(-20001, 'Order has no client');
END IF;

SELECT bonus_balance INTO v_balance
FROM client
WHERE id = v_client_id;

v_limit := ROUND(v_subtotal * 0.30, 2);
  v_to_spend := LEAST(p_amount, v_balance, v_limit);

  IF v_to_spend <= 0 THEN
    RAISE_APPLICATION_ERROR(-20002, 'Bonus amount must be > 0');
END IF;

INSERT INTO bonus_txn(client_id, order_id, txn_type, signed_amount, reason)
VALUES (v_client_id, p_order_id, 'SPEND', -v_to_spend, 'Spend bonuses');

UPDATE client
SET bonus_balance = bonus_balance - v_to_spend
WHERE id = v_client_id;

UPDATE orders
SET bonus_spent = v_to_spend,
    total      = GREATEST(v_subtotal - v_to_spend, 0)
WHERE id = p_order_id;

COMMIT;
END;
/

-- Завершение заказа
CREATE OR REPLACE PROCEDURE p_complete_order(
  p_order_id IN NUMBER
) AS
  v_client_id NUMBER;
  v_total     NUMBER(12,2);
  v_cashback  NUMBER(12,2);
BEGIN
SELECT client_id, total
INTO v_client_id, v_total
FROM orders
WHERE id = p_order_id;

UPDATE orders
SET status = 'COMPLETED',
    completed_at = SYSTIMESTAMP
WHERE id = p_order_id;

IF v_client_id IS NOT NULL THEN
    v_cashback := ROUND(v_total * 0.05, 2);
    IF v_cashback > 0 THEN
      INSERT INTO bonus_txn(client_id, order_id, txn_type, signed_amount, reason)
      VALUES (v_client_id, p_order_id, 'EARN', v_cashback, 'Cashback 5%');

UPDATE client
SET bonus_balance = bonus_balance + v_cashback
WHERE id = v_client_id;
END IF;
END IF;

COMMIT;
END;
/

------------------------------------------------------------
-- 3) VIEWS
------------------------------------------------------------

-- История бонусов клиентов
CREATE OR REPLACE VIEW v_client_bonus_history AS
SELECT
    c.phone,
    c.full_name,
    c.bonus_balance AS current_balance,
    b.txn_type,
    b.signed_amount,
    b.reason,
    b.order_id,
    b.created_at
FROM client c
         JOIN bonus_txn b ON b.client_id = c.id
ORDER BY b.created_at DESC;

-- Продажи по дням
CREATE OR REPLACE VIEW v_sales_by_day AS
SELECT
    TRUNC(created_at) AS day,
  COUNT(*) AS orders_count,
  SUM(total) AS total_revenue,
  SUM(bonus_spent) AS total_bonus_spent,
  AVG(total) AS avg_order_value
FROM orders
WHERE status = 'COMPLETED'
GROUP BY TRUNC(created_at)
ORDER BY day DESC;

-- Активные продукты по категориям
CREATE OR REPLACE VIEW v_active_products AS
SELECT
    pc.name AS category_name,
    p.id AS product_id,
    p.name AS product_name,
    p.description,
    p.price
FROM product p
         JOIN product_category pc ON pc.id = p.category_id
WHERE p.active = 'Y'
ORDER BY pc.name, p.name;

------------------------------------------------------------
-- 4) DEMO DATA
------------------------------------------------------------
INSERT INTO users(login, password_hash, role) VALUES ('barista1', 'hash', 'BARISTA');
INSERT INTO users(login, password_hash, role) VALUES ('admin1', 'hash', 'ADMIN');

INSERT INTO product_category(name) VALUES ('Кофе');
INSERT INTO product_category(name) VALUES ('Чай');
INSERT INTO product_category(name) VALUES ('Десерты');

INSERT INTO product(category_id, name, description, price, active)
SELECT id, 'Капучино', 'Эспрессо + молоко', 200, 'Y'
FROM product_category WHERE name='Кофе';

INSERT INTO product(category_id, name, description, price, active)
SELECT id, 'Латте', 'Молоко + эспрессо', 220, 'Y'
FROM product_category WHERE name='Кофе';

INSERT INTO product(category_id, name, description, price, active)
SELECT id, 'Чай черный', 'Классический черный чай', 160, 'Y'
FROM product_category WHERE name='Чай';

INSERT INTO product(category_id, name, description, price, active)
SELECT id, 'Чизкейк', 'Нью-Йорк чизкейк', 250, 'Y'
FROM product_category WHERE name='Десерты';

COMMIT;